language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - cd src
  #- cp myhelath/settings/local.sample.env myhelath/settings/local.env
  - python manage.py migrate --settings=settings.production
script:
  - python manage.py test profiles
