# Generated by Django 2.0.9 on 2019-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_auto_20190121_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
