# Generated by Django 2.0.9 on 2019-02-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0006_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
