# Generated by Django 2.0.9 on 2019-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0007_auto_20190205_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
