# Generated by Django 2.0.9 on 2019-02-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0008_auto_20190206_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='action',
            field=models.CharField(choices=[('sponsored', 'Sponsored'), ('cancelled', 'Cancelled')], default='sponsored', max_length=10),
        ),
    ]
