# Generated by Django 2.0.9 on 2019-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0009_sponsorship_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='action',
            field=models.CharField(choices=[('s', 'Sponsored'), ('c', 'Cancelled')], default='s', max_length=10),
        ),
    ]
