# Generated by Django 2.0.9 on 2019-02-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0010_auto_20190206_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='ended',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
